### ISSUE TITLE
Typing stops while changing browser tabs

### ISSUE THREAD

**Issue by martinbackes** [mntn-dev/t.js#1]
Hi Benjamin, is there a way that the typing doesnt stop in the background while I change tabs within the browser? I synced audio to the typewriting manually (hard coded), and when I change tabs for a while, my audio continues which is fine. But when I go back to my page, the typewriting paused and everything (audio + typewriting) is out of snyc. Is there a way to solve that?
Thanks

**Comment by mntn-dev** [comment]
thanks for reporting; it's an common, not _t.js_-specific _setInterval_ (which, in this case, wraps all the  typing activity) issue (lower priority on inactive windows/tabs -> slowdown) that can be fixed with _Web workers_. just include (something like) [HackTimer](https://github.com/turuslan/HackTimer) to your page;
example: ~~https://mn.tn/dev/t.js/tab/~~
(without: ~~https://mn.tn/dev/t.js/tab/?worker=0~~)

**Comment by martinbackes** [comment]
thanks a lot, I didn’t know that! so I only have to include those two lines within the header right? As easy as that?

for example:
<script type="text/javascript" src="/assets/js/HackTimer.min.js"></script>
<script type="text/javascript" src="/assets/js/HackTimerWorker.min.js"></script>

**Comment by mntn-dev** [comment]
yes, that's all.

**Comment by martinbackes** [comment]
great, thanks a lot :)
