### ISSUE TITLE
Publish on NPM

### ISSUE THREAD

**Issue by orditeck** [mntn-dev/t.js#6]
Would be useful!

**Comment by daviddavo** [comment]
Why not?

**Comment by mntn-dev** [comment]
well, i slowed down a bit. any quick how-to advice?

**Comment by daviddavo** [comment]
You have to simply run `npm init` and follow the steps. Be careful with the package naming as `tjs` already exists. You can always publish it in your user scope. But I think you can name it `t-js`.

Remember to add `jquery` as a dependency in a `packages.json` file with `npm install`.

Since GitHub recently implemented CI/CD with GitHub Actions, you can even set it up so it auto-publishes to npm when you put a tag in a commit.

https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry
